### ISSUE TITLE
load example,can see in System Dashboard,but can't access

### ISSUE THREAD

**Issue by orangeyts** [moqui/example#2]
**example 2.1.0 file:D:/git/moqui-framework/runtime/component/example  [moqui-camel]**

moqui-camel  1.0.0  file:D:/git/moqui-framework/runtime/component/moqui-camel  []

tools  2.1.0-rc1  file:D:/git/moqui-framework/runtime/base-component/tools  []

webroot  2.1.0-rc1  file:D:/git/moqui-framework/runtime/base-component/webroot  []

**Comment by jonesde** [comment]
Could you be more specific? What do you mean by "can't access" or in other words what did you try and what happened differently from what you expected?

**Comment by orangeyts** [comment]
step 1: gradle getComponent -Pcomponent=example
step 2: gradle run

expected:  example  can visited  like  tools component from  main menu,show some page

but:  main menu only  init two submenu,example  componet  can not be found,   but  under  Sysyem dashboard  can see info  (example,camel)

BTW:after  read your book,maybe  
'gradlew getComponent -Pcomponent=example'
only download  componet,not modify  root page of  example  OR  did not add  menu  db  record,so i can not  find  page

**Comment by jonesde** [comment]
You didn't mention loading data, and the root screen of the Example app is mounted by a database record. You also need authorization records, even for users in the general admin group. These records are in the ExampleSecurityData.xml file.

If you do a full load (ie 'gradle load') it will load these, but in an already running system just load the 'seed' data using the command line with the executable war file, or in the Tools app on the Data Import screen.

**Comment by orangeyts** [comment]
thank you very much.
