### ISSUE TITLE
gradle task for new componet

### ISSUE THREAD

**Issue by orangeyts** [moqui/example#3]
does framework has  auto create componet folder       structure ,

if no, can I  define in moqui-framework  Tasks in gradle  script and  PR.

**Comment by jonesde** [comment]
I might consider accepting a pull request for a gradle task to create a boilerplate component, but what would go in it? A component needs different things depending on the type of component it is (ie application, tool add on, integration, etc) and a base component doesn't need anything to function properly (the basic stuff is all by convention, not by configuration). Most of what would be in any generated component would not be used, and there are examples of every type of component to make it easier to add things like a build file for test only, build file where there is compiled src, component.xml file to add dependencies, etc.

Whatever the case this is the wrong repository for an issue like this. As you mentioned it would go in moqui-framework, so closing this issue.
